name: Terraform Apply

on:
  workflow_dispatch:
  push:
    paths:
      - "terraform/**"
    branches:
      - main

jobs:
  tf_fmt:
    name: Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './terraform/'
    steps:

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      
    - name: Checkout
      uses: actions/checkout@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve